environment:
  app_version: '7.4.0'

version: '$(app_version).{build}'

build: off

skip_branch_with_pr: true

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

install:
  - npm install

test_script:
  - npm start

artifacts:
  - path: '*.pdf'
    name: 'documentation'
